// Writes songs/library/.npmignore so the npm tarball carries only MIDI files whose
// provenance block records a redistributable licence. The JSON side files — the
// studio's own annotations and the provenance itself — always ship; a song whose
// .mid is withheld is "unfetched" at runtime and `ai-jam-sessions library fetch`
// pulls it from its recorded source under that source's terms.
//
// Run: pnpm exec tsx scripts/npm-ship-list.ts     (a test asserts the file is current)
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const REDISTRIBUTABLE = new Set(["CC-BY-SA-3.0-DE", "Public-Domain"]);
const HERE = dirname(fileURLToPath(import.meta.url));
export const LIBRARY_DIR = join(HERE, "..", "songs", "library");
export const NPMIGNORE = join(LIBRARY_DIR, ".npmignore");

export interface ShipRow { genre: string; id: string; licence: string; ships: boolean }

export function shipRows(libraryDir = LIBRARY_DIR): ShipRow[] {
  const rows: ShipRow[] = [];
  const genres = readdirSync(libraryDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
  for (const genre of genres) {
    const dir = join(libraryDir, genre);
    for (const f of readdirSync(dir).filter((x) => x.endsWith(".json")).sort()) {
      const id = f.slice(0, -5);
      const cfg = JSON.parse(readFileSync(join(dir, f), "utf8")) as {
        provenance?: { arrangement_license?: string };
      };
      const licence = cfg.provenance?.arrangement_license ?? "MISSING";
      rows.push({ genre, id, licence, ships: REDISTRIBUTABLE.has(licence) });
    }
  }
  return rows;
}

export function renderNpmignore(rows: ShipRow[]): string {
  const withheld = rows.filter((r) => !r.ships);
  const lines = [
    "# GENERATED by scripts/npm-ship-list.ts from each song's provenance block. Do not edit.",
    "# A .mid listed here has no verified redistributable licence and is withheld from the",
    "# npm tarball. Its .json (annotations + provenance) still ships; `ai-jam-sessions library",
    "# fetch` downloads the MIDI from the recorded source under that source's terms.",
    `# withheld: ${withheld.length} of ${rows.length}; shipped: ${rows.length - withheld.length}`,
    ...withheld.map((r) => `${r.genre}/${r.id}.mid`),
  ];
  return lines.join("\n") + "\n";
}

const isMain =
  !!process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));

if (isMain) {
  const rows = shipRows();
  const text = renderNpmignore(rows);
  const before = existsSync(NPMIGNORE) ? readFileSync(NPMIGNORE, "utf8") : "";
  writeFileSync(NPMIGNORE, text);
  const shipped = rows.filter((r) => r.ships).length;
  console.log(
    `${NPMIGNORE}: withheld ${rows.length - shipped}, shipped ${shipped}${before === text ? " (unchanged)" : ""}`,
  );
}
